# Generated by Django 6.0.4 on 2026-04-07 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('boolean', 'Yes/No'), ('choice', 'Single Choice'), ('multi', 'Multiple Choice'), ('text', 'Free Text'), ('scale', 'Scale 1-5')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(choices=[('basic', 'Basic'), ('security', 'Security Posture'), ('data', 'Data Handling'), ('infrastructure', 'Infrastructure'), ('industry_it', 'IT/SaaS Specific'), ('industry_banking', 'Banking Specific'), ('industry_healthcare', 'Healthcare Specific'), ('industry_insurance', 'Insurance Specific'), ('industry_government', 'Government Specific')], max_length=30)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('help_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='cloud_hosted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='data_sensitivity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='handles_financial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='handles_health',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='handles_pii',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='has_remote_workers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='num_third_party_vendors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ComplianceSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_name', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('priority', models.CharField(choices=[('required', 'Required'), ('recommended', 'Recommended'), ('optional', 'Optional')], max_length=20)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_responses', to='core.organization')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.onboardingquestion')),
            ],
            options={
                'unique_together': {('organization', 'question')},
            },
        ),
    ]
