# Generated by Django 6.0.4 on 2026-04-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_onboardingquestion_organization_cloud_hosted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingquestion',
            name='category',
            field=models.CharField(choices=[('basic', 'Basic'), ('security', 'Security Posture'), ('data', 'Data Handling'), ('infrastructure', 'Infrastructure'), ('industry_it', 'IT/SaaS Specific'), ('industry_banking', 'Banking Specific'), ('industry_healthcare', 'Healthcare Specific'), ('industry_insurance', 'Insurance Specific'), ('industry_government', 'Government Specific'), ('industry_ecommerce', 'E-Commerce Specific'), ('industry_telecom', 'Telecom Specific'), ('industry_pharma', 'Pharma Specific'), ('industry_energy', 'Energy Specific'), ('industry_manufacturing', 'Manufacturing Specific'), ('industry_nbfc', 'NBFC Specific'), ('industry_defence', 'Defence Specific')], max_length=30),
        ),
        migrations.AlterField(
            model_name='organization',
            name='industry',
            field=models.CharField(choices=[('it_saas', 'IT / SaaS'), ('banking', 'Banking / Fintech'), ('healthcare', 'Healthcare'), ('insurance', 'Insurance'), ('government', 'Government'), ('ecommerce', 'E-Commerce / Retail'), ('telecom', 'Telecommunications'), ('education', 'Education / EdTech'), ('manufacturing', 'Manufacturing / Industrial'), ('pharma', 'Pharmaceutical / Biotech'), ('energy', 'Energy / Power / Utilities'), ('legal', 'Legal / Law Firm'), ('logistics', 'Logistics / Supply Chain'), ('media', 'Media / Entertainment'), ('nbfc', 'NBFC / Microfinance'), ('realestate', 'Real Estate / PropTech'), ('defence', 'Defence / Aerospace')], max_length=50),
        ),
    ]
