# Generated by Django 6.0.4 on 2026-04-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditor', '0001_initial'),
        ('risks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditreview',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risks.risk'),
        ),
    ]
