# Generated by Django 6.0.4 on 2026-04-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('cvss_score', models.FloatField(default=0.0)),
                ('published_date', models.DateTimeField(null=True)),
                ('last_modified', models.DateTimeField(null=True)),
                ('affected_products', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapped_controls', models.ManyToManyField(blank=True, related_name='cves', to='compliance.control')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
