# Generated by Django 6.0.4 on 2026-04-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('alert_type', models.CharField(choices=[('critical_cve', 'Critical CVE'), ('missing_control', 'Missing Control'), ('vendor_risk', 'Vendor Risk Spike'), ('compliance_gap', 'Compliance Gap'), ('sla_breach', 'SLA Breach')], max_length=30)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compliance.control')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
