# Generated by Django 6.0.4 on 2026-04-07 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('cve_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='linked_cve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cve_manager.cve'),
        ),
    ]
