# Generated by Django 6.0.4 on 2026-04-09 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_reference', models.CharField(blank=True, help_text='e.g. Section 5(a), Clause 3.2', max_length=100)),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('modified', 'Modified')], max_length=20)),
                ('old_text', models.TextField(blank=True)),
                ('new_text', models.TextField(blank=True)),
                ('change_summary', models.TextField(blank=True, help_text='AI-generated summary of the change')),
                ('impact_score', models.IntegerField(default=0, help_text='1-10 impact severity score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-impact_score'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for auto-classification')),
                ('icon', models.CharField(blank=True, default='shield', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Compliance Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegulatorySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('rbi', 'Reserve Bank of India'), ('sebi', 'Securities and Exchange Board of India'), ('mca', 'Ministry of Corporate Affairs'), ('gazette', 'eGazette of India'), ('fiu', 'Financial Intelligence Unit')], max_length=20)),
                ('base_url', models.URLField()),
                ('scrape_url', models.URLField(help_text='URL to scrape for new notifications')),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('check_interval_minutes', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('product', 'Product/Service'), ('department', 'Department'), ('policy', 'Internal Policy'), ('process', 'Business Process'), ('system', 'IT System'), ('contract', 'Contract/Agreement')], max_length=20)),
                ('area_name', models.CharField(help_text='e.g. Home Loans, KYC Team, AML Policy', max_length=255)),
                ('description', models.TextField(blank=True, help_text='How this change affects the area')),
                ('risk_score', models.IntegerField(default=0, help_text='1-10 risk score')),
                ('action_required', models.TextField(blank=True, help_text='Specific action to take')),
                ('responsible_team', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='regulatory_intel.clausediff')),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='RegulatoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('doc_type', models.CharField(choices=[('circular', 'Circular'), ('notification', 'Notification'), ('master_direction', 'Master Direction'), ('act', 'Act/Statute'), ('amendment', 'Amendment'), ('guideline', 'Guideline')], max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=200)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('compliance_deadline', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='regulatory_docs/')),
                ('raw_text', models.TextField(blank=True, help_text='Extracted text content')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary')),
                ('impact_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('affected_entities', models.TextField(blank=True, help_text='Comma-separated list: banks, NBFCs, fintechs, etc.')),
                ('categories', models.TextField(blank=True, help_text='Comma-separated: KYC, prudential, cyber, etc.')),
                ('is_processed', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='regulatory_intel.regulatorydocument')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='regulatory_intel.regulatorysource')),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImpactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('executive_summary', models.TextField(blank=True)),
                ('detailed_analysis', models.TextField(blank=True)),
                ('policy_amendments', models.TextField(blank=True, help_text='Drafted policy amendment text')),
                ('sop_changes', models.TextField(blank=True, help_text='SOP update recommendations')),
                ('filing_checklist', models.TextField(blank=True, help_text='Required regulatory filings')),
                ('training_requirements', models.TextField(blank=True)),
                ('overall_risk_score', models.IntegerField(default=0)),
                ('generated_by', models.CharField(default='ai_agent', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='regulatory_intel.regulatorydocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clausediff',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diffs', to='regulatory_intel.regulatorydocument'),
        ),
        migrations.AddField(
            model_name='clausediff',
            name='previous_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forward_diffs', to='regulatory_intel.regulatorydocument'),
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('monitor', 'Monitor Agent'), ('scraper', 'Scraper Agent'), ('diff', 'Diff Agent'), ('classifier', 'Classifier Agent'), ('mapper', 'Mapping Agent'), ('drafter', 'Policy Drafting Agent'), ('reporter', 'Report Generation Agent')], max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='started', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regulatory_intel.regulatorydocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
