# Generated by Django 6.0.4 on 2026-04-09 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatIntelSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('dark_web', 'Dark Web Forum / Marketplace'), ('telegram', 'Telegram Channels'), ('osint', 'OSINT Feeds'), ('hactivist', 'Hacktivist Groups')], max_length=50)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('target_region', models.CharField(default='Global', max_length=100)),
                ('target_industry', models.CharField(default='Financial', max_length=100)),
                ('actor', models.CharField(blank=True, help_text='Known threat actor or APT group', max_length=100, null=True)),
                ('indicators_of_compromise', models.JSONField(blank=True, default=list, help_text='IPs, Domains, Hashes')),
                ('is_resolved', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat_intel.threatintelsource')),
            ],
        ),
        migrations.CreateModel(
            name='DarkWebMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_matched', models.CharField(max_length=100)),
                ('snippet', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.IntegerField(default=50, help_text='0-100 score formulated by AI Agent')),
                ('ai_analysis', models.TextField(blank=True, help_text='Agentic explanation of the threat context')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat_intel.threatintelsource')),
            ],
        ),
    ]
