# Generated by Django 6.0.4 on 2026-04-10 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_onboardingquestion_category_and_more'),
        ('threat_intel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('agent_type', models.CharField(choices=[('recon', 'Reconnaissance Agent'), ('darkweb_crawler', 'Dark Web Crawler'), ('email_hunter', 'Email Leak Hunter'), ('threat_analyzer', 'Threat Analyzer'), ('ioc_extractor', 'IOC Extractor'), ('report_generator', 'Report Generator'), ('orchestrator', 'Orchestrator Agent')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('active', 'Active'), ('scanning', 'Scanning'), ('analyzing', 'Analyzing'), ('error', 'Error'), ('cooldown', 'Cooldown')], default='idle', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('threats_found', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('capabilities', models.JSONField(default=list, help_text='List of agent capabilities')),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='livethreat',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livethreat',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threatintelsource',
            name='source_type',
            field=models.CharField(choices=[('dark_web', 'Dark Web Forum / Marketplace'), ('telegram', 'Telegram Channels'), ('osint', 'OSINT Feeds'), ('hactivist', 'Hacktivist Groups'), ('paste_site', 'Paste Sites'), ('breach_db', 'Breach Databases')], max_length=50),
        ),
        migrations.CreateModel(
            name='DarkWebScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('org_search', 'Organization Search'), ('email_search', 'Email Search'), ('domain_monitor', 'Domain Monitor'), ('full_recon', 'Full Reconnaissance')], max_length=50)),
                ('query', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('results_summary', models.TextField(blank=True)),
                ('results_data', models.JSONField(blank=True, default=dict)),
                ('agent_used', models.CharField(default='RECON_AGENT', max_length=100)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('total_breaches_found', models.IntegerField(default=0)),
                ('total_mentions_found', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('CLEAN', 'Clean')], default='LOW', max_length=20)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='threat_intel.agenttask')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='threat_intel.threatagent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success'), ('critical', 'Critical')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='threat_intel.threatagent')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LeakedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('breach_source', models.CharField(help_text='Where the leak was found', max_length=255)),
                ('breach_date', models.DateField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('data_types', models.JSONField(default=list, help_text='Types of data leaked: password, hash, phone, etc.')),
                ('password_hash', models.CharField(blank=True, help_text='Partial hash if found', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=50)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaked_creds', to='threat_intel.monitoreddomain')),
            ],
            options={
                'unique_together': {('email', 'breach_source')},
            },
        ),
    ]
